# Generated by Django 3.1.3 on 2021-06-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Fiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=11)),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('correo', models.CharField(default='correo@correo.com', max_length=75)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('estado_cliente', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empleado', models.CharField(max_length=11)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('direccion_empleado', models.CharField(max_length=200)),
                ('telefono_empleado', models.CharField(max_length=20)),
                ('cargo_empleado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Pedido',
            fields=[
                ('id_orden_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('descripcion', models.CharField(default='Descripcion', max_length=200)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.BooleanField(default=True, verbose_name='Enabled')),
                ('empleado_rut_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('familia_producto', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('tipo_producto', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion', max_length=100)),
                ('precio', models.IntegerField(default=1, verbose_name='Precio')),
                ('nombre_producto', models.CharField(default='', max_length=50)),
                ('marca_producto', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=1, verbose_name='Stock')),
                ('stock_critico', models.IntegerField(default=1, verbose_name='Critical stock')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rubro_empresa', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('telefono_proveedor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Comprobante',
            fields=[
                ('id_tipo_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Venta',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Descripcion', max_length=100)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('monto', models.IntegerField(default=0)),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('vigente', models.BooleanField(default=True)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente_fiado')),
                ('id_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipo_venta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_Fiado',
            fields=[
                ('id_venta_fiado', models.AutoField(primary_key=True, serialize=False)),
                ('vigente', models.BooleanField(default=True)),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente_fiado')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_Detalle',
            fields=[
                ('id_venta_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('monto', models.BigIntegerField()),
                ('vigente', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Mensual',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('total_productos', models.IntegerField()),
                ('total_ganancias', models.IntegerField()),
                ('venta_id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion_Pedido',
            fields=[
                ('id_recepcion_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField()),
                ('total_pedido', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('recepcion_id_orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orden_pedido')),
            ],
        ),
        migrations.AddField(
            model_name='orden_pedido',
            name='proveedor_id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_comprobante')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
    ]
