# Generated by Django 3.2.3 on 2021-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210613_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
