# Generated by Django 3.1.3 on 2021-05-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210518_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, default='dd/mm/yyyy'),
        ),
    ]
