# Generated by Django 3.1.3 on 2021-05-19 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210518_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
