# Generated by Django 3.1.3 on 2021-05-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210518_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejhemplo',
            fields=[
                ('id_boleta2', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta2', models.DateField()),
                ('cantidad_productos2', models.IntegerField()),
                ('monto_neto2', models.IntegerField()),
                ('monto_total2', models.IntegerField()),
            ],
        ),
    ]
