# Generated by Django 3.1.3 on 2021-05-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ejhemplo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, default='%m/%d/%y'),
        ),
    ]
