# Generated by Django 3.1.3 on 2021-05-19 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210518_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ejhemplo',
        ),
    ]
