# Generated by Django 3.1.3 on 2021-05-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210521_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_pedido',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=200),
        ),
    ]
