# Generated by Django 3.2.3 on 2021-05-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210522_2006'),
        ('core', '0012_orden_pedido_descripcion'),
    ]

    operations = [
    ]
