# Generated by Django 3.1.3 on 2021-06-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210602_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion_pedido',
            name='descripcion',
            field=models.CharField(default='Descripcion', max_length=200),
        ),
    ]
